---
driver:
  name: vagrant
  box: win2012

provisioner:
  name: chef_zero

platforms:
  - name: win2012

verifier:
  name: pester

suites:
  - name: default
    run_list:
      - recipe[mssql-demo::default]
    attributes:
