name             'mssql-demo'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures mssql-demo'
long_description 'Installs/Configures mssql-demo'
version          '0.1.0'
